# Build config for ebay-java-oauth-client
language: java
dist: trusty

env:
  global:
    - CODECOV_TOKEN: 75491e14-a163-4190-b535-630ed880a466

os:
  - linux

sudo: required
addons:
  chrome: stable

install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N http://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - mvn clean install -DskipTests=true
  - mvn test -B

before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

after_success:
  - bash <(curl -s https://codecov.io/bash)